Numpy

In [2]:
import numpy as np

In [3]:
#Cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [4]:
#Criar o array com um tipo especifico - como float de 64 bits e depois como int de 32 bits
mtfloat = np.array([1, 2, 3], dtype= np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype= np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
#Mudar o tipo do Array - Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
#Quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [6]:
#Fazendo o Inverso também
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [7]:
#Criando um array bidimensional
mt7 = np.array([[7,2,23], [12,27,4], [5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [8]:
#Criar arrays vazios tipificados - Empty significa que não são diferenciados, não que são vazios
vazio = np.empty([3,2], dtype= int)
print(vazio)
print("-----------")
#Cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("----------")
#Com valores igual a um
um = np.ones([5,7])
print(um)
print("------------")
#Cria Matriz quadrada com diagonal principal com valores 1 e os outros valores Zero
diagonal = np.eye(5)
print(diagonal)

[[3403141796824350720                1720]
 [                  0       1674877900224]
 [                  0   14636698789019905]]
-----------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
#Valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print("------------")
#Valores aleatórios distr. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print("-------------")
#Valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.00598448 0.92847082 0.10394634 0.13815375 0.86930576]
------------
[ 0.53755454 -0.58320699 -0.81167164 -0.18071494 -0.06660896]
-------------
[[1.69314094 2.30390088 9.47058505 2.81307572]
 [6.61738794 3.59178986 3.11225993 8.77976542]
 [3.11528063 9.01761758 3.5017591  7.05179392]]


In [10]:
#Outra forma de gerar aleatórios - Uso de Semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)
#Gerar inteiros
ale6 = gnr.integers(10, size=(3, 4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [11]:
#UNIQUE - remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 16, 17, 17, 12, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [12]:
#Funções Específicas - Cria a Matriz Bidimensional k
k = np.array([[17,22,43], [27,25,14], [15,24,32]])
print(k)
#Mostrando um elemento de k
print(k[0][1])
#Mostrando o tamanho das dimensões de k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [13]:
#Funções Matemáticas
#Mostra o maior valor de k
print(k.max())
#Mostra o menor valor de k
print(k.min())
#Mostra a soma dos valores de k
print((k.sum()))
#Mostra o valor da média dos valores de k
print(k.mean())
#Mostra o valor do desvio padrão (standard deviation) dos valores de k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [14]:
#Funções Universais - Aplicadas a todos os Elementos
#Raiz Quadrada de todos os elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
#Exponencial de todos os elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [15]:
#Extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
# Mostra o elemento da Posição 2
print(m[1])
print("------------")
# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("--------------")
# Mostra o array criado a partir da segunda posição - até todo o restante do array
print(m[1:])
print("------------")
# Mostra o array criado a partir da antepenúltima posição até o final
print(m[-3:])

2
------------
[1 2]
--------------
[2 3 4 5 6]
------------
[4 5 6]


In [16]:
#Extração de Linhas e Colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("---------")
#Primeira Linha, todas as colunas
l_linha1 = l[0, :]
print(l_linha1)
print("-------------")
#Segunda Linha
l_linha2 = l[1, :]
print(l_linha2)
print("----------")
#Terceira Linha
l_linha3 = l[2, :]
print(l_linha3)
print("--------------")
#Todas as linhas, primeira coluna
l_coluna1 = l[:, 0]
print(l_coluna1)
print("-------------")
#Todas as linhas, segunda coluna
l_coluna2 = l[:, 1]
print(l_coluna2)

[[4 5]
 [6 1]
 [7 4]]
---------
[4 5]
-------------
[6 1]
----------
[7 4]
--------------
[4 6 7]
-------------
[5 1 4]


In [17]:
#Adição e Multiplicação de Matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n+o
print(res1)
print("-----------")
res2 = n*o
print(res2)
print("------------")
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q)

[[2 3]
 [4 5]]
-----------
[[1 2]
 [3 4]]
------------
[[3 3]
 [5 5]
 [7 7]]


In [18]:
#Transposição - Rearranja um conjunto de 15 elementos de 0 a 14 em 3 linhas e 5 colunas
f = np.arange(15).reshape((3, 5))
print(f)
print("------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [19]:
#Outro modo
r = np.arange(15).reshape((3, 5))
print(r)
print("-------")
# rearranja um conjunto de 15 elementos 
# mostra a matrizes transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [20]:
#Expressões Lógicas - Usando Where - Criando Matriz com Valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
# Criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
# Criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[-1.05828437  0.34540292  0.51454273 -2.0367983 ]
 [ 1.04496987  0.01456975 -1.08766657  0.59137307]
 [-0.33131117 -0.92598255 -1.23164738 -0.10298124]
 [-0.18519894  0.29603321 -1.43019535  1.41976788]]
[[False  True  True False]
 [ True  True False  True]
 [False False False False]
 [False  True False  True]]
[[-1  1  1 -1]
 [ 1  1 -1  1]
 [-1 -1 -1 -1]
 [-1  1 -1  1]]
